name: autofix.ci

on:
  pull_request:
  push:
    branches: ['main']

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run formatting
      - uses: autofix-ci/action@v1
